# If you change this file restart server.

# Site
title: "API | Smartlook"
company_url: "https://www.smartlook.com/"
company_email: info@smartlook.com
baseurl: "" # root folder of your Jekyll site

# Misc
highlighter: rouge

# Build
markdown: kramdown
exclude:
  - readme.md
  - Gemfile 
  - Gemfile.lock