# IF YOU CHANGE THIS FILE RESTART SERVER!

# site
title: "API | Smartlook"
description: "Smartlook API. Tricks and tips for developers."
baseurl: "" # root folder of Jekyll site, by default, baseurl is set to "" (never set to "/")
url: "" # = ?

# custom variables
product_name: "Smartlook.com"
product_url: "https://www.smartlook.com/"
product_email: info@smartlook.com
help_url: "https://www.smartlook.com/help/"

# server
livereload: true

# build
markdown: kramdown

exclude:
  - readme.md
  - Gemfile 
  - Gemfile.lock

# build: DOCS
collections:
  docs:
    permalink: /:collection/:path/
    output: true

defaults:
  - scope:
      path: _docs
      type: docs
    values:
      layout: page